# Generated by Django 4.1.3 on 2022-11-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, verbose_name='nom')),
                ('first_name', models.CharField(max_length=200, verbose_name='prénom')),
                ('birthday', models.DateField()),
            ],
        ),
    ]
